[project]
name = "personal-claude"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "textual>=7.5.0",
    "textual-dev>=1.8.0",
    "watchfiles>=1.1.1",
]
